services:
  - type: web
    name: multi-asset-backtesting-engine
    runtime: python
    plan: free
    region: singapore
    branch: main
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=src streamlit run app/streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.3
